blank_issues_enabled: true
contact_links:
  - name: For debugging help or technical support
    url: https://ansible-rulebook.readthedocs.io/en/latest/contributing.html
    about: For general debugging or technical support please see the linked section of our docs.

  - name: ğŸ“ Ansible Code of Conduct
    url: https://docs.ansible.com/ansible/latest/community/code_of_conduct.html?utm_medium=github&utm_source=issue_template_chooser
    about: EDA-Controlles uses the Ansible Code of Conduct; â¤ Be nice to other members of the community. â˜® Behave.

  - name: ğŸ’¼ For Enterprise
    url: https://www.ansible.com/use-cases/event-driven-automation
    about: Red Hat offers support for the Ansible Automation Platform
